var content = `
点击排行::https://m.wuxiamh.com/rank/click/searchPage/&&订阅排行::https://m.wuxiamh.com/rank/subscribe/searchPage&&发布::https://m.wuxiamh.com/list/click/searchPage/&&更新::https://m.wuxiamh.com/list/update/searchPage/&&点击::https://m.wuxiamh.com/list/post/searchPage/&&连载::https://m.wuxiamh.com/list/lianzai/update/searchPage/&&完结::https://m.wuxiamh.com/list/wanjie/update/searchPage/&&儿童::https://m.wuxiamh.com/list/ertong/update/searchPage/&&少年::https://m.wuxiamh.com/list/shaonian/update/searchPage/&&少女::https://m.wuxiamh.com/list/shaonv/update/searchPage/&&青年::https://m.wuxiamh.com/list/qingnian/update/searchPage/&&日本::https://m.wuxiamh.com/list/riben/update/searchPage/&&大陆::https://m.wuxiamh.com/list/dalu/update/searchPage/&&欧美::https://m.wuxiamh.com/list/oumei/update/searchPage/&&其他::https://m.wuxiamh.com/list/qita/update/searchPage/&&悬疑::https://m.wuxiamh.com/list/xuanyi/searchPage/&&东方::https://m.wuxiamh.com/list/dongfang/searchPage/&&欢乐向::https://m.wuxiamh.com/list/huanlexiang/searchPage/&&爱情::https://m.wuxiamh.com/list/aiqing/searchPage/&&科幻::https://m.wuxiamh.com/list/kehuan/searchPage/&&搞笑::https://m.wuxiamh.com/list/gaoxiao/searchPage/&&舰娘::https://m.wuxiamh.com/list/jianniang/searchPage/&&校园::https://m.wuxiamh.com/list/xiaoyuan/searchPage/&&百合::https://m.wuxiamh.com/list/baihe/searchPage/&&魔法::https://m.wuxiamh.com/list/mofa/searchPage/&&轻小说::https://m.wuxiamh.com/list/qingxiaoshuo/searchPage/&&冒险::https://m.wuxiamh.com/list/maoxian/searchPage/&&四格::https://m.wuxiamh.com/list/sige/searchPage/&&职场::https://m.wuxiamh.com/list/zhichang/searchPage/&&音乐舞蹈::https://m.wuxiamh.com/list/yinyuewudao/searchPage/&&侦探::https://m.wuxiamh.com/list/zhentan/searchPage/&&竞技::https://m.wuxiamh.com/list/jingji/searchPage/&&奇幻::https://m.wuxiamh.com/list/qihuan/searchPage/&&生活::https://m.wuxiamh.com/list/shenghuo/searchPage/&&治愈::https://m.wuxiamh.com/list/zhiyu/searchPage/&&其他::https://m.wuxiamh.com/list/qita/searchPage/&&格斗::https://m.wuxiamh.com/list/gedou/searchPage/&&伪娘::https://m.wuxiamh.com/list/weiniang/searchPage/&&热血::https://m.wuxiamh.com/list/rexue/searchPage/&&神鬼::https://m.wuxiamh.com/list/shengui/searchPage/&&惊悚::https://m.wuxiamh.com/list/jingsong/searchPage/&&萌系::https://m.wuxiamh.com/list/mengxi/searchPage/&&节操::https://m.wuxiamh.com/list/jiecao/searchPage/&&纯爱::https://m.wuxiamh.com/list/chunai/searchPage/&&颜艺::https://m.wuxiamh.com/list/yanyi/searchPage/&&魔幻::https://m.wuxiamh.com/list/mohuan/searchPage/&&美食::https://m.wuxiamh.com/list/meishi/searchPage/&&历史::https://m.wuxiamh.com/list/lishi/searchPage/&&战争::https://m.wuxiamh.com/list/zhanzheng/searchPage/&&性转换::https://m.wuxiamh.com/list/xingzhuanhuan/searchPage/&&西方魔幻::https://m.wuxiamh.com/list/xifangmohuan/searchPage/&&高清单行::https://m.wuxiamh.com/list/gaoqingdanxing/searchPage/

`;

var arr = content.split("&&");
var str = "";
for (var i = 0;i < arr.length; i ++) {
  var temp = arr[i] + "@Header:{\"user-agent\": \"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1\"}";

  str += temp+"&&";

}

console.log(str);